### ISSUE TITLE
No fields are populating

### ISSUE THREAD

**Issue by jr00ck** [jupitercow/gravity-forms-post-updates#1]
Hey Jake,

Glad you're back in business on this plugin. I just tested this latest version 1.2.16 and the same problem that was introduced for a lot of people in version 1.2.13 is present in this version. I already shared my latest code with you on Bitbucket, which rolls back some of the changes in 1.2.13 to what was in 1.2.11 and populating fields works. 

Not sure if it's only for CPTs, but that is where no fields are populating for me.

If I can get time, I might fork and send a pull request, but not sure if I can get to that before next week.

**Comment by jupitercow** [comment]
It is the CPT issue. I am working on that now. Will have an update by the
end of the weekend if all goes well. Thanks!

**Comment by jr00ck** [comment]
I submitted a pull request with the fixes. Once accepted, this can be closed. Thanks.
